
const fs = require('fs');
const path = require('path');
const {promisify} = require('util');

const [,, outputFileName, jsonFile, pngFile] = process.argv;

console.log('OUTPUT FILE', outputFileName);
console.log('JSON FILE', jsonFile);
console.log('PNG FILE', pngFile);

(async () => {
    const contents = await promisify(fs.readFile)(pngFile);
    const url = `data:image/png;base64,${contents.toString('base64')}`

    let outputFile = '// Generated by generate.js\n'
        + `export const image = "${url}";\n`;
    const jsonData = JSON.parse(await promisify(fs.readFile)(jsonFile));
    for (const tag of jsonData.meta.frameTags) {
        const {name, from} = tag;
        const frameData = jsonData.frames[from];
        outputFile += `export const ${name} = ${Math.floor(frameData.frame.x /  16)};\n`;
    }

    outputFile += `export const nImages = ${jsonData.meta.frameTags.length};\n`

    await promisify(fs.writeFile)(outputFileName, outputFile, 'utf8');
})().catch(console.error);