// Generated by generate.js
export const image = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAAAQCAMAAAA4YYPKAAAAAXNSR0IArs4c6QAAADlQTFRFHyMbISAeKBUOMDAwNSERX19fYatNZgAAaalhdk43d2A9edtfilUumBwIpKSktJBawJhbz9XW3R8IqGVP6AAAAWJJREFUSMfNl4uugyAMhrmI25wy2fs/7BGhSLkEFFzOP0fTuCx+afuDRKlJy4WzOe8sEogVtAQaAxGlnlouKPXRciHO8e+5QOKJnFPz7JSn76OcvJA04LwJVq11E6xs+SIt4xtpJNMHaQrzYgWjB/brcQlw8D7EkM0uGLLVhTJgQcWeigGPTCYAc/8CLaq5BvhugLMPOFuw1cUy4BMpqmBFC54DpEiQC2HzqIKGa78OQLZfdYCFFj0PeBBKcamCw1FDC+gtzPLB0t6ivQElUuyiiQpCewIgtGcVoLVDK+eaVlUuGeXc8VUDPh65GWQwfmCiMH67idYAYqDbAXdFxfMAQxdtBLyhRS2hFJkKUmqqp6O3neRnsKlF+7voFUDfZBIu2mQy/V3UEEohqmYw2DbS+2DLNnFHi5YBj1jhov9sozdRisoKRke1YAZbj2qlw/VFwPxhuwjY+bD969ehX78u/QE96G5EQMAzPAAAAABJRU5ErkJggg==";
export const sticky_piston_face = 0;
export const piston_face = 1;
export const piston_side = 2;
export const sticky_piston_side = 3;
export const piston_back = 4;
export const observer_arrow = 5;
export const observer_side = 6;
export const observer_face = 7;
export const observer_back = 8;
export const note_block = 9;
export const redstone_lamp_off = 10;
export const redstone_lamp_lit = 11;
export const redstone_block = 12;
export const slime_block = 13;
export const nImages = 14;
