// Generated by generate.js
export const image = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANAAAAAQCAMAAABQkgHyAAAAAXNSR0IArs4c6QAAADNQTFRFHyMbISAeKBUOMDAwNSERX19fZgAAaalhdk43d2A9ilUumBwIpKSktJBawJhbz9XW3R8IRdRcsQAAAVlJREFUSMfFl4uSgyAMRXlIXZVK//9rV4QAITCA1d1bJZNpx/E0yRWZMYtVCKO5vFksk2hoy8SMma1CMOZtFQLN8e+lQpKFXHJ3r1yWv0c5+0GyQOshWK32Q7CK7YO0seWNtOR5s0LkBtP/+xLQlHyYI1lDcCR7CBSooWaPUKCY6QJQ7SrQcpZjgvMAWlOg1YPsIVKgGYlUqKOlxoA4EuRK+ZxUyHGcRwQS51EGarTcOFAk0upShaZYIw+ULMLzwDLecncDaSTqcoUKQbsBELRbEcjblVdwNa8uFyO5DDzdQK9XbYYEjA+YHIzPaXIlIAzwONApUpwEKHe5QaAHWs4TaVWpEOeuOjYm9l6foaGWu9/lrgClplBwuSFTuN/lHJFWqmuGMhsvP4dGbPuJlmsDxdjhcv/8YHVRq84Kka1PNkOjW5/WZvQiUH1z2gT6cnP6168HT78+/AJN41s6v2IcJgAAAABJRU5ErkJggg==";
export const sticky_piston_face = 0;
export const piston_face = 1;
export const piston_side = 2;
export const sticky_piston_side = 3;
export const piston_back = 4;
export const observer_arrow = 5;
export const observer_side = 6;
export const observer_face = 7;
export const observer_back = 8;
export const note_block = 9;
export const redstone_lamp_off = 10;
export const redstone_lamp_lit = 11;
export const redstone_block = 12;
export const nImages = 13;
